name: terraform-plan
on:
  push:
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - run: terraform init
      - run: terraform plan -lock=false -out terraform.tf
      # generate plain output
      - run: terraform show -no-color terraform.tf > terraform.text
      # generate json output
      - run: terraform show -json terraform.tf > terraform.json
      - uses: actions/checkout@v2
        ##ofrisror/action-terraform-report@v2
        with:
          # tell the action the plan outputs
          terraform-text: ${{ github.workspace }}/terraform.text
          terraform-json: ${{ github.workspace }}/terraform.json
